name: GitHub Actions Demo
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.11'
      - run: dotnet test
  build:
    runs-on: ubuntu-latest
    name: build
    needs: tests
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-veion: '5.0.11'
      - name: Build library
        run: dotnet build --configuration Release
      - name: Pack library
        run: dotnet pack --no-build --configuration Release ./DofusRE/DofusRE.csproj --output .
      - name: Publish library
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
